modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="orbitalcannon"
version="1.2.0"  # <-- this must be a string, not a number-only field
displayName="Orbital Cannon"
authors="FoxyWoxy" #optional
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # if nothing is specified, MATCH_VERSION is the default when clientSideOnly=false, otherwise IGNORE_ALL_VERSION when clientSideOnly=true (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''do /orbital that input either nuke or stab for nuke the ring size for stab the stab depth and the delay
Uses /orbital <nuke|stab> <value> <delay> to give a fishing rod configured and named (0 durability).

nuke <rings> <delay> = ring-based CUBIC-METRES style nuke (rings = number of rings).

stab <depth> <delay> = ring/column stab (depth = how deep).

delay = ticks before the strike spawns (counts down after you right-click the rod)

Adds gamerules:

doOrbital — master toggle for the entire system.

doOrbital5xDamageAll — 5× damage (applies by increasing explosion radius → affects blocks & entities).

doOrbital5xDamageOnlyPlayers — attempts to multiply player damage from orbital explosions (applies extra damage to players only).

doOrbital5xDamageOnlyBlocks — increases explosion radius so block damage is multiplied.

doOrbital1useCreative makes it so every shot it one use in creative or not
(in survival no matter what each shot is one use)'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
